#!/bin/bash
#$ -cwd
#$ -q BrainLab.owner
#$ -pe orte 20
#$ -N parallel
#$ -o par.o
#$ -e par.e

export PATH=/usr/lib64/openmpi-1.5.3/bin/:$PATH
export LD_LIBRARY_PATH=/home/garethf/usr/lib:$LD_LIBRARY_PATH

/usr/lib64/openmpi-1.5.3/bin/mpirun -np $NSLOTS ./parallel-dynamic $1 $2