#! /bin/bash
#$ -cwd
#$ -q BrainLab.owner
#$ -N sequential
#$ -o seq.o
#$ -e seq.e

export LD_LIBRARY_PATH=/home/garethf/usr/lib:$LD_LIBRARY_PATH

i="500"
while [ $i -le 10000 ]
do

  ./sequential $i $i
  ./sequential $i $i
  ./sequential $i $i
  ./sequential $i $i
  ./sequential $i $i
  ./sequential $i $i
  ./sequential $i $i
  ./sequential $i $i
  ./sequential $i $i
  ./sequential $i $i

  i=$[$i+500]
done
